import './globals.css';

import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import React from 'react';

const raleway = Raleway({ subsets: ['cyrillic-ext'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`scrollbar scrollbar-track-gray-900 scrollbar-thumb-purple-500 scrollbar-thumb-rounded-md ${raleway}`}
      >
        {children}
      </body>
    </html>
  );
}
